import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  const username = process.env.ADMIN_USERNAME || "qendrimi";
  const password = process.env.ADMIN_PASSWORD || "Lendriti.1";
  const passwordHash = await bcrypt.hash(password, 12);

  const existing = await prisma.adminUser.findFirst();
  if (existing) {
    await prisma.adminUser.update({
      where: { id: existing.id },
      data: { email: username, name: username, passwordHash },
    });
  } else {
    await prisma.adminUser.create({
      data: { email: username, name: username, passwordHash },
    });
  }

  await prisma.inquiry.deleteMany();
  await prisma.document.deleteMany();
  await prisma.photo.deleteMany();
  await prisma.machine.deleteMany();

  const machines = [
    {
      slug: "volvo-ec220e-2021",
      category: "excavator",
      manufacturer: "Volvo",
      model: "EC220E",
      year: 2021,
      askingPrice: 118000,
      location: "Mitrovicë",
      country: "Kosovo",
      condition: "used",
      availability: "immediately",
      stockNumber: "LG-EX-2201",
      serialNumber: "VCECW220L00012345",
      description:
        "Well-maintained Volvo EC220E crawler excavator from a single-owner fleet. Full service history, hydraulic quick coupler and two buckets. Ready for immediate inspection in Mitrovicë.",
      sellerInfo: "Lendriti Group SHPK, Mitrovicë",
      additionalInfo: "CE documentation available. Transport can be arranged throughout the Balkans and EU.",
      status: "active",
      featured: true,
      hours: 4850,
      fuelType: "Diesel",
      enginePower: "129 kW / 173 hp",
      excavatorSpecs: {
        operatingHours: "4850",
        operatingWeight: "22100",
        engineManufacturer: "Volvo",
        engineModel: "D6J",
        enginePower: "129 kW / 173 hp",
        fuelType: "Diesel",
        emissionClass: "Stage V",
        bucketCapacity: "1.15",
        maxDiggingDepth: "6.7",
        maxReach: "9.9",
        maxDiggingHeight: "9.6",
        hydraulicSystem: "Volvo electro-hydraulic",
        hydraulicFlow: "424",
        hydraulicPressure: "355",
        trackWidth: "600",
        trackCondition: "Good",
        undercarriageCondition: "Good",
        numberOfBuckets: "2",
        quickCoupler: "Hydraulic",
        attachments: "Hydraulic breaker piping, 2 buckets, ripper",
        airConditioning: "Yes",
        cabin: "ROPS/FOPS, heated seat",
        radio: "Yes",
        additionalEquipment: "Rear camera, LED work lights, central lubrication",
        serviceHistory: "Full dealer service history available",
        lastService: "March 2026 / 4,700 h",
        inspection: "Ready for export inspection",
      },
      purchasePrice: 92000,
      purchaseDate: new Date("2025-11-12"),
      supplier: "Nordic Fleet Oy",
      purchaseLocation: "Tampere, Finland",
      transportCost: 3200,
      repairCost: 1800,
      otherPurchaseCosts: 400,
      seoTitle: "Volvo EC220E 2021 for sale | Lendriti Group SHPK",
      seoDescription: "Volvo EC220E excavator, 2021, 4,850 hours. Stage V, hydraulic coupler. Available in Mitrovicë, Kosovo.",
      photos: [{ url: "/images/machines/volvo-ec220e.png", alt: "Volvo EC220E excavator", isMain: true }],
    },
    {
      slug: "caterpillar-320-2022",
      category: "excavator",
      manufacturer: "Caterpillar",
      model: "320",
      year: 2022,
      askingPrice: 132000,
      location: "Mitrovicë",
      country: "Kosovo",
      condition: "used",
      availability: "immediately",
      stockNumber: "LG-EX-3202",
      serialNumber: "CAT0320ELHBT01234",
      description:
        "Late-model Caterpillar 320 with low hours and Grade 2D ready wiring. Clean undercarriage and original paint. Ideal for earthworks and utility contractors.",
      sellerInfo: "Lendriti Group SHPK",
      additionalInfo: "Factory warranty transfer possible subject to Caterpillar terms.",
      status: "active",
      featured: true,
      hours: 2100,
      fuelType: "Diesel",
      enginePower: "121 kW / 162 hp",
      excavatorSpecs: {
        operatingHours: "2100",
        operatingWeight: "21500",
        engineManufacturer: "Caterpillar",
        engineModel: "C4.4",
        enginePower: "121 kW / 162 hp",
        fuelType: "Diesel",
        emissionClass: "Stage V",
        bucketCapacity: "1.00",
        maxDiggingDepth: "6.7",
        maxReach: "9.9",
        maxDiggingHeight: "9.6",
        hydraulicSystem: "Cat Advanced Hydraulic",
        hydraulicFlow: "429",
        hydraulicPressure: "350",
        trackWidth: "600",
        trackCondition: "Excellent",
        undercarriageCondition: "Excellent",
        numberOfBuckets: "1",
        quickCoupler: "Hydraulic",
        attachments: "GP bucket, hydraulic coupler",
        airConditioning: "Yes",
        cabin: "Deluxe cab, rearview camera",
        radio: "Yes",
        additionalEquipment: "Product Link, LED lights",
        serviceHistory: "CAT dealer maintained",
        lastService: "January 2026",
        inspection: "Available on request",
      },
      purchasePrice: 108000,
      purchaseDate: new Date("2026-02-04"),
      supplier: "Rhein Machine Handel",
      purchaseLocation: "Cologne, Germany",
      transportCost: 2800,
      repairCost: 0,
      otherPurchaseCosts: 650,
      seoTitle: "Caterpillar 320 2022 for sale | Lendriti Group",
      seoDescription: "Caterpillar 320 excavator 2022, 2,100 hours, Stage V. Professional used equipment from Lendriti Group SHPK.",
      photos: [{ url: "/images/machines/caterpillar-320.png", alt: "Caterpillar 320 excavator", isMain: true }],
    },
    {
      slug: "komatsu-pc210lc-11-2020",
      category: "excavator",
      manufacturer: "Komatsu",
      model: "PC210LC-11",
      year: 2020,
      askingPrice: 98000,
      location: "Mitrovicë",
      country: "Kosovo",
      condition: "used",
      availability: "short",
      stockNumber: "LG-EX-2103",
      description:
        "Komatsu PC210LC-11 reserved for a client. Strong working machine with recent track work and documented service.",
      status: "reserved",
      featured: false,
      hours: 7200,
      fuelType: "Diesel",
      enginePower: "123 kW / 165 hp",
      excavatorSpecs: {
        operatingHours: "7200",
        operatingWeight: "21900",
        engineManufacturer: "Komatsu",
        engineModel: "SAA6D107E-3",
        enginePower: "123 kW / 165 hp",
        fuelType: "Diesel",
        emissionClass: "Stage IV",
        bucketCapacity: "1.2",
        trackCondition: "Good",
        undercarriageCondition: "Good",
        quickCoupler: "Mechanical",
        airConditioning: "Yes",
        lastService: "November 2025",
      },
      purchasePrice: 74000,
      purchaseDate: new Date("2025-08-20"),
      supplier: "Balkan Plant Ltd",
      purchaseLocation: "Skopje, North Macedonia",
      transportCost: 900,
      repairCost: 4200,
      otherPurchaseCosts: 200,
      seoTitle: "Komatsu PC210LC-11 2020 | Lendriti Group",
      seoDescription: "Komatsu PC210LC-11 excavator, 2020, 7,200 hours. Currently reserved.",
      photos: [{ url: "/images/machines/komatsu-pc210.png", alt: "Komatsu PC210LC excavator", isMain: true }],
    },
    {
      slug: "volvo-fh16-2021",
      category: "truck",
      manufacturer: "Volvo",
      model: "FH16 750",
      year: 2021,
      askingPrice: 89000,
      location: "Mitrovicë",
      country: "Kosovo",
      condition: "used",
      availability: "immediately",
      stockNumber: "LG-TR-1601",
      serialNumber: "YV2RT40A8MB123456",
      description:
        "Volvo FH16 750 4x2 tractor unit. I-Shift, Globetrotter XL cabin, retarder and full air suspension. Suitable for heavy international haulage.",
      sellerInfo: "Lendriti Group SHPK",
      additionalInfo: "EU specification. Tachograph and ADR documents can be prepared.",
      status: "active",
      featured: true,
      kilometres: 412000,
      fuelType: "Diesel",
      transmission: "I-Shift",
      enginePower: "551 kW / 750 hp",
      truckSpecs: {
        kilometresDriven: "412000",
        firstRegistration: "03.2021",
        engine: "D16K750",
        enginePower: "551 kW / 750 hp",
        engineDisplacement: "16100",
        fuelType: "Diesel",
        emissionClass: "Euro 6",
        transmission: "I-Shift",
        numberOfGears: "12",
        axles: "2",
        wheelConfiguration: "4x2",
        grossVehicleWeight: "18",
        payload: "11.2",
        trailerCoupling: "Jost 2\" fifth wheel",
        suspension: "Air",
        cabinType: "Globetrotter XL",
        sleepingCabin: "Yes",
        airConditioning: "Yes",
        pto: "Yes",
        hydraulicSystem: "No",
        tankCapacity: "810",
        tyres: "315/70 R22.5",
        tyreCondition: "Good",
        serviceHistory: "Volvo service contracts until 2025",
        inspection: "TÜV valid until 09.2026",
        previousOwners: "1",
        additionalEquipment: "Retarder, fridge, parking cooler, extra tanks",
      },
      purchasePrice: 72000,
      purchaseDate: new Date("2025-12-03"),
      supplier: "Svensk Lastbil AB",
      purchaseLocation: "Gothenburg, Sweden",
      transportCost: 2100,
      repairCost: 950,
      otherPurchaseCosts: 350,
      seoTitle: "Volvo FH16 750 2021 for sale | Lendriti Group",
      seoDescription: "Volvo FH16 750 tractor, 2021, 412,000 km, Euro 6, I-Shift. Available from Lendriti Group SHPK, Kosovo.",
      photos: [{ url: "/images/machines/volvo-fh16.png", alt: "Volvo FH16 tractor truck", isMain: true }],
    },
    {
      slug: "scania-r450-2019",
      category: "truck",
      manufacturer: "Scania",
      model: "R450",
      year: 2019,
      askingPrice: 54000,
      location: "Mitrovicë",
      country: "Kosovo",
      condition: "used",
      availability: "immediately",
      stockNumber: "LG-TR-4502",
      description:
        "Scania R450 Highline 4x2. Opticruise, retarder and well-kept cabin. Honest kilometres and recent clutch work.",
      status: "active",
      featured: false,
      kilometres: 687000,
      fuelType: "Diesel",
      transmission: "Opticruise",
      enginePower: "331 kW / 450 hp",
      truckSpecs: {
        kilometresDriven: "687000",
        firstRegistration: "06.2019",
        engine: "DC13 155",
        enginePower: "331 kW / 450 hp",
        fuelType: "Diesel",
        emissionClass: "Euro 6",
        transmission: "Opticruise",
        numberOfGears: "12",
        wheelConfiguration: "4x2",
        cabinType: "Highline",
        sleepingCabin: "Yes",
        airConditioning: "Yes",
        tyreCondition: "Fair",
        previousOwners: "2",
        inspection: "Valid until 04.2027",
      },
      purchasePrice: 41000,
      purchaseDate: new Date("2026-01-18"),
      supplier: "Alpen Truck GmbH",
      purchaseLocation: "Graz, Austria",
      transportCost: 1400,
      repairCost: 2200,
      otherPurchaseCosts: 180,
      seoTitle: "Scania R450 2019 for sale | Lendriti Group",
      seoDescription: "Scania R450 2019 tractor unit, 687,000 km, Euro 6. Lendriti Group SHPK, Mitrovicë.",
      photos: [{ url: "/images/machines/scania-r450.png", alt: "Scania R450 truck", isMain: true }],
    },
    {
      slug: "man-tgx-18-510-2020",
      category: "truck",
      manufacturer: "MAN",
      model: "TGX 18.510",
      year: 2020,
      askingPrice: 62000,
      location: "Mitrovicë",
      country: "Kosovo",
      condition: "used",
      availability: "immediately",
      stockNumber: "LG-TR-5103",
      description: "MAN TGX 18.510 GX cabin. Sold to a Balkan haulier. Record kept for internal reporting.",
      status: "sold",
      featured: false,
      kilometres: 534000,
      fuelType: "Diesel",
      transmission: "TipMatic",
      enginePower: "375 kW / 510 hp",
      truckSpecs: {
        kilometresDriven: "534000",
        firstRegistration: "09.2020",
        engine: "D2676",
        enginePower: "375 kW / 510 hp",
        fuelType: "Diesel",
        emissionClass: "Euro 6d",
        transmission: "TipMatic",
        wheelConfiguration: "4x2",
        cabinType: "GX",
        sleepingCabin: "Yes",
        airConditioning: "Yes",
      },
      purchasePrice: 48000,
      purchaseDate: new Date("2025-06-10"),
      supplier: "München Nutzfahrzeuge",
      purchaseLocation: "Munich, Germany",
      transportCost: 1900,
      repairCost: 800,
      otherPurchaseCosts: 250,
      actualSellingPrice: 58500,
      saleDate: new Date("2026-03-14"),
      buyer: "Dukagjini Transport SHPK",
      sellingCosts: 400,
      otherSaleCosts: 150,
      saleNotes: "Sold after inspection. Buyer arranged own transport.",
      seoTitle: "MAN TGX 18.510 2020 | Lendriti Group",
      seoDescription: "MAN TGX 18.510 tractor, 2020. Sold by Lendriti Group SHPK.",
      photos: [{ url: "/images/machines/man-tgx.png", alt: "MAN TGX truck", isMain: true }],
    },
    {
      slug: "liebherr-ltm-1050-2018",
      category: "other",
      manufacturer: "Liebherr",
      model: "LTM 1050-3.1",
      year: 2018,
      askingPrice: 285000,
      location: "Mitrovicë",
      country: "Kosovo",
      condition: "used",
      availability: "immediately",
      stockNumber: "LG-OT-1050",
      description:
        "Liebherr LTM 1050-3.1 mobile crane, 50 t class. Regular inspections and complete lifting documentation. A serious machine for rental fleets and contractors.",
      additionalInfo: "Hook block, counterweights and current inspection certificates included.",
      status: "active",
      featured: true,
      hours: 6100,
      fuelType: "Diesel",
      enginePower: "270 kW",
      otherSpecs: {
        machineType: "All-terrain mobile crane",
        operatingHours: "6100",
        operatingWeight: "36 t travel / 50 t class",
        engine: "Liebherr diesel",
        enginePower: "270 kW",
        fuelType: "Diesel",
        dimensions: "3-axle AT crane",
        additionalEquipment: "LICCON, working-range limiter, radio remote",
        serviceHistory: "Annual crane inspection completed 2025",
        inspection: "Valid load test certificate",
      },
      purchasePrice: 240000,
      purchaseDate: new Date("2025-10-02"),
      supplier: "Central Crane Europe",
      purchaseLocation: "Linz, Austria",
      transportCost: 6500,
      repairCost: 3200,
      otherPurchaseCosts: 1100,
      seoTitle: "Liebherr LTM 1050-3.1 2018 for sale | Lendriti Group",
      seoDescription: "Liebherr LTM 1050-3.1 mobile crane, 2018, 6,100 hours. Available from Lendriti Group SHPK.",
      photos: [{ url: "/images/machines/liebherr-crane.png", alt: "Liebherr mobile crane", isMain: true }],
    },
    {
      slug: "jcb-3cx-2019",
      category: "other",
      manufacturer: "JCB",
      model: "3CX",
      year: 2019,
      askingPrice: 42000,
      location: "Mitrovicë",
      country: "Kosovo",
      condition: "used",
      availability: "immediately",
      stockNumber: "LG-OT-3CX",
      description:
        "JCB 3CX backhoe loader with 4-in-1 bucket and extending dipper. Reliable site machine, recently serviced.",
      status: "active",
      featured: false,
      hours: 3900,
      fuelType: "Diesel",
      enginePower: "74 kW / 100 hp",
      otherSpecs: {
        machineType: "Backhoe loader",
        operatingHours: "3900",
        operatingWeight: "8200 kg",
        engine: "JCB EcoMAX",
        enginePower: "74 kW / 100 hp",
        fuelType: "Diesel",
        additionalEquipment: "4-in-1 shovel, extending dipper, palleted forks",
        lastService: "February 2026",
      },
      purchasePrice: 33500,
      purchaseDate: new Date("2026-01-09"),
      supplier: "Adriatic Plant",
      purchaseLocation: "Durrës, Albania",
      transportCost: 450,
      repairCost: 700,
      otherPurchaseCosts: 80,
      seoTitle: "JCB 3CX 2019 for sale | Lendriti Group",
      seoDescription: "JCB 3CX backhoe loader, 2019, 3,900 hours. Lendriti Group SHPK, Kosovo.",
      photos: [{ url: "/images/machines/jcb-3cx.png", alt: "JCB 3CX backhoe loader", isMain: true }],
    },
    {
      slug: "mercedes-actros-1845-2018",
      category: "truck",
      manufacturer: "Mercedes-Benz",
      model: "Actros 1845",
      year: 2018,
      askingPrice: 39000,
      location: "Mitrovicë",
      country: "Kosovo",
      condition: "used",
      status: "sold",
      featured: false,
      kilometres: 812000,
      fuelType: "Diesel",
      transmission: "Automatic",
      enginePower: "330 kW / 449 hp",
      truckSpecs: {
        kilometresDriven: "812000",
        firstRegistration: "04.2018",
        engine: "OM 471",
        emissionClass: "Euro 6",
        transmission: "PowerShift 3",
        wheelConfiguration: "4x2",
        cabinType: "StreamSpace",
        sleepingCabin: "Yes",
      },
      purchasePrice: 36000,
      purchaseDate: new Date("2025-04-22"),
      supplier: "Italia Truck srl",
      purchaseLocation: "Trieste, Italy",
      transportCost: 800,
      repairCost: 2600,
      otherPurchaseCosts: 120,
      actualSellingPrice: 37500,
      saleDate: new Date("2025-09-30"),
      buyer: "Private haulier, Prishtina",
      sellingCosts: 200,
      otherSaleCosts: 0,
      saleNotes: "Sold slightly below total investment after extra repairs.",
      seoTitle: "Mercedes-Benz Actros 1845 2018 | Lendriti Group",
      seoDescription: "Mercedes-Benz Actros 1845, 2018. Sold by Lendriti Group SHPK.",
      photos: [{ url: "/images/machines/man-tgx.png", alt: "Mercedes Actros tractor", isMain: true }],
    },
  ];

  for (const item of machines) {
    const { photos, ...data } = item;
    const created = await prisma.machine.create({ data });
    await prisma.photo.create({
      data: {
        machineId: created.id,
        url: photos[0].url,
        alt: photos[0].alt,
        isMain: true,
        orderIndex: 0,
      },
    });
  }

  await prisma.inquiry.create({
    data: {
      name: "Arben Krasniqi",
      email: "arben.k@example.com",
      phone: "+383 44 111 222",
      message: "I am interested in the Volvo EC220E. Can it be inspected this week?",
    },
  });

  await prisma.pageContent.upsert({
    where: { key: "about" },
    update: {},
    create: {
      key: "about",
      contentEn:
        "Lendriti Group SHPK buys and sells excavators, trucks and other heavy machinery from our yard in Mitrovicë, Kosovo. We work with contractors and dealers across Europe who need honest machines, clear paperwork and a direct counterpart.",
    },
  });

  console.log("Seeded Lendriti Group marketplace.");
  console.log(`Admin login: ${username}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
